services:
  # Database
  mysql:
    image: mysql:8.0
    container_name: healthcare-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: healthcare_db
      MYSQL_USER: healthcare
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - healthcare-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Auth Service
  auth-service:
    build:
      context: ./services/auth-cervice
      dockerfile: Dockerfile
    container_name: auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/healthcare_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: healthcare
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - healthcare-network

  # Doctor Service
  doctor-service:
    build:
      context: ./services/doctor-service
      dockerfile: Dockerfile
    container_name: doctor-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/healthcare_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: healthcare
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8082
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - healthcare-network

  # Payment Service
  payment-service:
    build:
      context: ./services/payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/healthcare_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: healthcare
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8086
    ports:
      - "8086:8086"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - healthcare-network

  # Appointment Service
  appointment-service:
    build:
      context: ./services/appointment-service
      dockerfile: Dockerfile
    container_name: appointment-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/healthcare_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: healthcare
      SPRING_DATASOURCE_PASSWORD: 123456
      SERVER_PORT: 8085
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - healthcare-network

 # Frontend
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8081
    depends_on:
      - auth-service
      - doctor-service
      - appointment-service
      - payment-service
    networks:
      - healthcare-network

volumes:
  mysql_data:

networks:
  healthcare-network:
    driver: bridge
