apiVersion: v1
kind: Secret
metadata:
  name: healthcare-secrets
  namespace: smart-healthcare
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "root"
  MYSQL_DATABASE: "healthcare_db"
  MYSQL_USER: "healthcare"
  MYSQL_PASSWORD: "123456"
  SPRING_MAIL_USERNAME: "dilanavishka183@gmail.com"
  SPRING_MAIL_PASSWORD: "pllb iekj knmu scuc"
  APP_JWT_SECRET: "my-super-secret-key-change-this-in-production"
  PAYHERE_MERCHANT_ID: "1235016"
  PAYHERE_MERCHANT_SECRET: "MTA3ODk5Njg4MzM2Mzk1OTcwNjkzMDkyMzE5NTUyMTA2NzQ5OTk2"

